stages:
  data_ingestion:
    cmd: python src/pipeline/data_ingestion.py
    deps: #Depends on 
    - src/pipeline/data_ingestion.py
    - config/config.yaml
    outs: # output it gives
    - data/raw
  data_preprocessing:
    cmd: python src/pipeline/data_preprocessing.py
    deps:
    - data/raw
    - config/config.yaml
    - src/pipeline/data_preprocessing.py
    outs:
    - data/processed
  feature_engineering:
    cmd: python src/pipeline/feature_engineering.py
    deps:
    - config/config.yaml
    - data/processed
    - src/pipeline/feature_engineering.py
    outs:
    - data/features
  model_building:
    cmd: python src/pipeline/model_building.py
    deps:
    - config/config.yaml
    - data/features
    - src/pipeline/model_building.py
    outs:
    - artifacts/models
  predictions:
    cmd: python src/pipeline/predictions.py
    deps:
    - artifacts/models
    - config/config.yaml
    - data/features
    - src/pipeline/predictions.py
    metrics:
    - artifacts/metrics
